### ISSUE TITLE
Test OSDF health on `-classad` plugin initialization

### ISSUE THREAD

**Issue by djw8605** [htcondor/osdf-client#1]
When the osdf client is first called on the EP with the `-classad` argument, it should test the OSDF "health".

Initial thoughts:
- Test download of a monitoring file on startup.
- Only advertise the osdf and stash protocols if monitoring is successful.

**Comment by bbockelm** [comment]
Closing as we are instead putting a generic health check mechanism into the file transfer plugin.  Will no longer be needed once https://github.com/htcondor/htcondor/pull/1218 is done.
