### ISSUE TITLE
stashcp fails to locate caches when HTTP_PROXY is invalid

### ISSUE THREAD

**Issue by bbockelm** [htcondor/osdf-client#13]
If `HTTP_PROXY` is set to a non-functioning (or simply a DNS name that doesn't resolve), then the cache discovery process fails with messages like this:

```
DEBUG[2022-11-17T20:34:10-06:00] Querying http://128.142.248.156/stashservers.dat?list=xroots 
ERROR[2022-11-17T20:34:10-06:00] Could not open URL Get "http://128.142.248.156/stashservers.dat?list=xroots": proxyconnect tcp: dial tcp: lookup red-proxy1.unl.edu on 129.93.239.153:53: no such host 
```

A dead proxy shouldn't be completely fatal to the client, especially if we're not using HTTP.

**Comment by djw8605** [comment]
Fixed in #14
