### ISSUE TITLE
Device code flow for acquiring tokens

### ISSUE THREAD

**Issue by bbockelm** [htcondor/osdf-client#25]
When a client registration is present for a given issuer -- and no other token is discovered - we should pull the token from the configuration and generate a new one through either a refresh flow or a device code flow as necessary.

**Comment by djw8605** [comment]
I haven't found a great device code flow golang library.  I have some code that I've used in the past though, but I don't really want to maintain our own device code flow components.

Will continue googling...

**Comment by bbockelm** [comment]
Fixed in #27.
