### ISSUE TITLE
Handle stash and osdf URLs with 2 slashes

### ISSUE THREAD

**Issue by matyasselmeci** [htcondor/osdf-client#33]
Some users get tripped up by requiring 3 slashes after the schema (`stash:///` instead of `stash://`) and it's hard to figure out the problem is from the resulting error (403 forbiddens with the first part of the path chopped off).

If the `URL.Host` component of a stash or osdf URL is non-empty, prepend it and a leading slash to the path (so `osdf://foo/bar` is treated the same as `osdf:///foo/bar`).

**Comment by djw8605** [comment]
I could have sworn we accounted for this here: https://github.com/htcondor/osdf-client/blob/a8d598e4cb15977376f4f6fc7d73a259d56972d2/main.go#L274-L276

Ah, maybe this is for destination files?
