### ISSUE TITLE
Env var for bypassing `http_proxy`

### ISSUE THREAD

**Issue by bbockelm** [htcondor/osdf-client#37]
When `stash_plugin` is run by HTCondor, it inherits the job runtime environment -- making it difficult to have a job use `http_proxy` but to avoid the proxy (often, Squid) for the file transfers itself.  In some simple testing, a nearby OSDF cache might be >10x faster than what Squid can do.

I don't want to change the defaults right now but since it's hard to subtract out `http_proxy`, can we add a new environment variable to have just stash* ignore the proxy?

**Comment by djw8605** [comment]
How about:
`OSDF_DISABLE_HTTP_PROXY`

When set, never use an HTTP proxy, even if http_proxy is set in the environment.

Our current environment variables are very inconsistent, why not continue the trend?

**Comment by bbockelm** [comment]
How about `<PREFIX>_DISABLE_HTTP_PROXY` and then we keep a global list of known prefixes  .... and clean up other variables to do the same?

**Comment by bbockelm** [comment]
This was fixed in #38.
