### ISSUE TITLE
Stop reading job ad

### ISSUE THREAD

**Issue by matyasselmeci** [htcondor/osdf-client#61]
We read and parse the job ad file in [main.go:parse_job_ad()](https://github.com/htcondor/osdf-client/blob/main/main.go#L479) for getting Owner and ProjectName info of the job.  We used to send that to monitoring but no longer do as of #50.

That function crashes if `$_CONDOR_JOB_AD` is set to a non-existent or unreadable file, but instead of fixing it we should just remove the `parse_job_ad()`.

**Comment by djw8605** [comment]
We use it in the #41, but it can certainly be improved.

**Comment by matyasselmeci** [comment]
Ah, fair enough. In that case, we should just fix that crash.
