### ISSUE TITLE
Support HTCondor's funky `_` schemes

### ISSUE THREAD

**Issue by bbockelm** [htcondor/osdf-client#67]
HTCondor will, in some cases, add an `_` character into the file transfer scheme.  When this occurs, transfers with the OSDF plugin will fail.

See the following bug report: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1731

Here's how we solved it for HTTP: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1011

It's an ugly solution -- simply "corrects" the URL prior to feeding it to the URL parsing library.  Can we pull the same stunt for OSDF as well?

**Comment by bbockelm** [comment]
@CohenQU - can you please take a look at this?

**Comment by CohenQU** [comment]
Sure.
